INSERT INTO tipo_despesa(nome_despesa) VALUES ('Agua')
INSERT INTO tipo_despesa(nome_despesa) VALUES ('Luz')
INSERT INTO tipo_despesa(nome_despesa) VALUES ('Telefone')
INSERT INTO tipo_despesa(nome_despesa) VALUES ('IPTU')
INSERT INTO tipo_despesa(nome_despesa) VALUES ('Internet')
INSERT INTO tipo_despesa(nome_despesa) VALUES ('Hospedagem de Dominio')
INSERT INTO tipo_despesa(nome_despesa) VALUES ('Combustivel')
INSERT INTO tipo_despesa(nome_despesa) VALUES ('Insumos Gerais')
INSERT INTO tipo_despesa(nome_despesa) VALUES ('Alimentação')
INSERT INTO tipo_despesa(nome_despesa) VALUES ('Transporte')
INSERT INTO tipo_despesa(nome_despesa) VALUES ('Compras Diversas')

INSERT INTO tipo_receita(nome_receita) VALUES ('Mensalidade')
INSERT INTO tipo_receita(nome_receita) VALUES ('Doação')
INSERT INTO tipo_receita(nome_receita) VALUES ('Venda')
INSERT INTO tipo_receita(nome_receita) VALUES ('Prestação de Serviços')
INSERT INTO tipo_receita(nome_receita) VALUES ('Ganho por exibições na Internet')
INSERT INTO tipo_receita(nome_receita) VALUES ('Direitos Conexos')
INSERT INTO tipo_receita(nome_receita) VALUES ('Direitos Autorais')
